#!/usr/bin/env python
"""
Script for starting Pydra Node.
"""
import os
import pydra

pydra_root = pydra.__file__[:pydra.__file__.rfind('/')]
os.system('twistd -ny %s/twisted/node.tac --pidfile=node.pid' % pydra_root)

