#!/usr/bin/env python
"""
Script for starting Pydra Master.
"""
import os
import pydra

pydra_root = pydra.__file__[:pydra.__file__.rfind('/')]
os.system('twistd -ny %s/twisted/master.tac' % pydra_root)

