#!/usr/bin/env python
"""
Script for starting Pydra Node.
"""
import os
import pydra
from pydra import config

pydra_root = pydra.__file__[:pydra.__file__.rfind('/')]
os.system('twistd -ny %s/twisted/node.tac --pidfile=%s/node.pid' \
                % (pydra_root, config.RUNTIME))

